### ISSUE TITLE
Erreur dans le readme paragraphe enabling digital signature

### ISSUE THREAD

**Issue by jerrywham** [24eme/signaturepdf#110]
Il manque un "s" à libnss3-tools dans la commande :

`sudo apt-get install poppler-utils libnss3-tool `

Ce qui fait qu'il n'est pas possible de trouver l'outil et l'installer.

**Comment by wincelau** [comment]
Merci c'est rectifié : https://github.com/24eme/signaturepdf/commit/77a7c37b9c3c18dfe6fab784a72385f6be77e64d !
