### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jerrywham** [24eme/signaturepdf#111]
`pdfsign error: Segmentation fault [/var/www/signaturepdf/lib/NSSCryptography.class.php:28]`
est l'erreur qui s'affiche à la génération d'un pdf signé chiffré.

Dans le fichier config/config.ini, j'ai les lignes suivantes (le mot de passe ci-dessous n'est que pour l'exemple mais est de longueur à peu prêt équivalente) :
```
NSS3_DIRECTORY=../NSS/
NSS3_PASSWORD="CKWUQI5NMxhuESMnkyY7LcL3Xq514zOcgSwDC4gGoHnvVR1G0owCjsO0inBsR2v2cSvrs"
NSS3_NICK="monnickperso"
```

**Comment by wincelau** [comment]
Ah top j'allais te répondre ça !

Merci j'ai modifié la doc : https://github.com/24eme/signaturepdf/commit/fdf4ebe6c45b629bed352ee1e48db76123f0e8d6

**Comment by wincelau** [comment]
Tu peux utiliser okular (un client lourd). Le travail n'est pas complétement terminé on va intégrer un vérificateur à signature pdf

**Comment by wincelau** [comment]
Je viens de découvrir cet outil en ligne pour vérifier une signature : https://it-tools.tech/pdf-signature-checker
