### ISSUE TITLE
Impossible d'intégrer le site dans une iframe

### ISSUE THREAD

**Issue by djangoliv** [24eme/signaturepdf#24]
Quand je tente d'afficher le site https://pdf.24eme.fr/ (ou mon propre déploiement) dans une iframe, firefox refuse de l'afficher.

![Screenshot 2022-03-01 at 11-31-51 Screenshot](https://user-images.githubusercontent.com/13416971/156153488-ec453a0b-b938-4b49-9d61-bbc5ee5b1647.png)

**Comment by wincelau** [comment]
J'ai désactivé l'entête http `X-Frame-Options` qui était configuré par défaut à `SOMEORIGIN` par le framework php fatfree, ce qui interdisait l'utilisation en iframe : 8495642ab8e73f5442678872bbf7c10e01034223

L'iframe fonctionne maintenant : `data:text/html,<html><head></head><body><iframe src="https://pdf.24eme.fr" height="600" width="1000"></iframe></body></html>`

**Comment by xgaia** [comment]
Merci @wincelau !

**Comment by djangoliv** [comment]
Merci !
