### ISSUE TITLE
Indiquer les conditions de conservations ou non du PDF sur le serveur

### ISSUE THREAD

**Issue by teymour** [24eme/signaturepdf#26]

**Comment by wincelau** [comment]
Fait : ac8279e43e54aeedfaeabd859d371b58f1373813 62d6a7c0c3e81086d32ba66ee8541ae4aa1dc643 a787b82d45d255d522ff2ef5fc14832c6b67f699

**Comment by wincelau** [comment]
Ajouter une case de consetement du stockage du PDF sur le serveur pour le partage pourrait être une bonne chose et de pouvoir au passage choisir une durée de conservation sur le serveur : #32

**Comment by wincelau** [comment]
Identique #32
