### ISSUE TITLE
PDF en multisignature : chiffrer le pdf et les calques sur le serveur

### ISSUE THREAD

**Issue by teymour** [24eme/signaturepdf#27]
En multisignature, le PDF et les calques des signatures sont stockés sur le serveur.

Pour un service mis à disposition publiquement, il serait utile que ces fichiers soient stockés chiffré.

L'url de partage pourrait être constituée d'une ancre contenant une clé symétrique de chiffrement. Ainsi le détenteur du serveur ne pourrait pas lire les fichiers. La clé ne transiterait alors qu'en POST et ne serait donc pas lisible dans les logs du serveur.

**Comment by wincelau** [comment]
Fait https://github.com/24eme/signaturepdf/releases/tag/v1.6.0
