### ISSUE TITLE
ne fonctionne pas avec Firefox

### ISSUE THREAD

**Issue by Marc-Flender** [24eme/signaturepdf#41]
Bonjour,
Superbe application.
Elle  fonctionne très bien sur Chromium.
Malheureusement,  ça ne fonctionne pas sur Firefox (version testée: 95.0 en safe mode donc sans aucune extension)
Que manque-t-il pour que ça fonctionne avec Firefox?
Merci

**Comment by wincelau** [comment]
Bonjour,

Merci pour votre retour :-).

A quel moment ou après quelle action le problème survient-t-il ?

**Comment by Marc-Flender** [comment]
Bonjour,

recrificatif : ça fonctionne sur un Macbook avec la version récente de Firefox.
Sur mon PC linux mint, et sur un autre PC linux debian à jour, ca bloque au moment du chargement du PDF.
Rien ne s'affiche, et donc le menu de droite ne s'affiche pas non plus.
Peut-être puis-je utiliser l'Inspecteur de Firefox pour en savoir plus, si vous me guidez.
Peut-être manque-t-il des paquets dont aurait besoin  FIrefox sur mon PC?

**Comment by wincelau** [comment]
Oui pour l'inspecteur et notamment la console pour voir l'erreur ça aiderait bien :-).

On peut ouvrir l'inspecteur avec F12 (ou clique droit "Inspecter"), ça devrait ouvrir une bar en bas ou à droite. Puis en cliquant sur l'onglet "Console" de cette bar ou (Ctrl + Shift + K), on peut voir les erreurs elles sont en général en rouge.

**Comment by Marc-Flender** [comment]
Bonjour,
Au démarrage de la page Web, l'erreur dans la console est:
`Uncaught (in promise) DOMException: The operation is insecure.` : ligne 999 de signature.js  dont le code est:
`const cache = await caches.open('pdf');`

Ensuite je clique sur "tester avec un pdf de demo": rien ne se passe.
La console affiche
```
Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/bootstrap.min.js?5.1.3
Source Map URL: bootstrap.min.js.map

Uncaught (in promise) DOMException: The operation is insecure. [signature.js:999](https://pdf.24eme.fr/js/signature.js?202204270035)
Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/pdf.js?legacy
Source Map URL: pdf.js.map

Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/opentype.min.js?1.3.3
Source Map URL: opentype.min.js.map
```

**Comment by Marc-Flender** [comment]
Bonjour,
Au démarrage de la page Web, l'erreur dans la console est:
`Uncaught (in promise) DOMException: The operation is insecure.` : ligne 999 de signature.js  dont le code est:
`const cache = await caches.open('pdf');`

Ensuite je clique sur "tester avec un pdf de demo": rien ne se passe.
La console affiche
```
Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/bootstrap.min.js?5.1.3
Source Map URL: bootstrap.min.js.map

Uncaught (in promise) DOMException: The operation is insecure. [signature.js:999](https://pdf.24eme.fr/js/signature.js?202204270035)
Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/pdf.js?legacy
Source Map URL: pdf.js.map

Source map error: Error: request failed with status 404
Resource URL: https://pdf.24eme.fr/vendor/opentype.min.js?1.3.3
Source Map URL: opentype.min.js.map
```

**Comment by wincelau** [comment]
OK merci :-) ! 

Ça semble être à cause de la connexion qui n'est pas sécurisé on peut le savoir grâce au cadenas à gauche de la barre d'url.

S’il est comme ça c'est que ce n'est pas sécurisé :

![unsecure_connexion](https://user-images.githubusercontent.com/6379869/200201624-19b4adc6-5fa7-4e9b-9e63-d69725dffdda.png)

**Comment by Marc-Flender** [comment]
Bonjour,
Non la connexion est sécurisée.
Sur le même ordinateur, je constate que ça ne fonctionne pas avec Firefox, Palemoon, mais ok avec Chrome.
Quand je veux utiliser le pdf de test sur Firefox, l'erreur de l'inspecteur est la ligne 999 de signature.js
`const cache = await caches.open('pdf');`
Je suppose qu'il attend indéfinement l'ouverture du PDF.  Firefox ne dot pas bien faire cette opération

En revanche, si j'utilise le partage de document entre plusieurs personnes, je peux bien ouvrir le lien dans Firefox.

**Comment by milouse** [comment]
Bonjour,

Je viens de tomber sur la même erreur et j’ai un peu galéré à trouver, mais c’est en fait assez stupide : étiez-vous par hasard, comme moi, en mode de navigation privée ? En effet les accès disque (et donc le cache) sont désactivé en mode navigation privé par Firefox, d'où le plantage (c.f. [Bugzilla 1724607](https://bugzilla.mozilla.org/show_bug.cgi?id=1724607)).

Dans une fenêtre de navigation normale aucun souci de fonctionnement.

Ceci étant dit, un petit try/catch autour de [cette ligne](https://github.com/24eme/signaturepdf/blob/master/public/js/signature.js#L1004) serait peut-être intéressant ? Qu’en pensez-vous ?

```javascript
…
try {
    const cache = await caches.open('pdf');
} catch (e) {
    console.error(e)
    alert("Erreur d'accès au cache. Cette application ne fonctionne pas en mode de navigation privée");
    return;
}
…
```

**Comment by Marc-Flender** [comment]
Bonjour, 
Bravo! Ca fonctionne quand je réautorise la sauvegarde de l'historique.

**Comment by wincelau** [comment]
Trop bien merci d'avoir trouvé :pray: !

Oui ça serait bien j'ai appliqué la modification que tu conseilles : a1509a554f384ccbdc54479d2b8e1dfb7c5cdb9f

Je me suis permis de te mettre auteur du commit (mais je peux l'enlever si tu ne préfères pas)

**Comment by milouse** [comment]
@wincelau Ahah, merci beaucoup pour l’attribution :) J’ai hésité à faire une MR directement ne connaissant pas trop les usages/wording. Désolé si ça vous a pris plus de temps.

**Comment by wincelau** [comment]
Pas de soucis, j'ai fait ça avec le plaisir d'ajouter un nouveau contributeur au projet :).
