### ISSUE TITLE
Internationaliser / traduire le projet

### ISSUE THREAD

**Issue by wincelau** [24eme/signaturepdf#48]
Internationalisation des interfaces de l'application

**Comment by wayneoutthere** [comment]
Je peux, avec mon temps libre, essayez a traduire project en anglais?  est ce qu'il y a une liste des strings ou quelque chose comme weblate ou je peux essayez?  Merci :)

**Comment by wincelau** [comment]
Le développement est terminé et release :  https://github.com/24eme/signaturepdf/releases/tag/v1.4.0

La contribution à la traduction et l'ajout de nouvelles langues est possible ici : https://hosted.weblate.org/projects/signature-pdf/application/

**Comment by maupao** [comment]
Italian Translation added

**Comment by jerrywham** [comment]
La traduction ne se fait pas. Le cookie de langue est bien modifié mais cela n'a pas d'impact sur l'interface qui reste en anglais.
L'application a l'url d'un sous-domaine de mon domaine principal. Est-ce que ça pourrait venir de là ?
Je n'ai pas d'erreur dans la console. Ça fonctionne en local mais pas en ligne.
www-data a les droits en lecture/écriture sur le dossier locale.
J'avoue ne pas comprendre.

**Comment by wincelau** [comment]
Est-ce que tu pourrais partager l'url de ton instance ?

Peut-être que les locales sont mal configurés.

Tu l'as déployé par docker ou toi même ?

**Comment by jerrywham** [comment]
J'ai déployé par moi-même depuis le zip téléchargé par curl.
Les dépendances ont été déployées avant. En aurais-je oublié ?

```php
	/etc/php/8.2/apache2/conf.d/10-mysqlnd.ini,
	/etc/php/8.2/apache2/conf.d/10-opcache.ini,
	/etc/php/8.2/apache2/conf.d/10-pdo.ini,
	/etc/php/8.2/apache2/conf.d/15-xml.ini,
	/etc/php/8.2/apache2/conf.d/20-apcu.ini,
	/etc/php/8.2/apache2/conf.d/20-bcmath.ini,
	/etc/php/8.2/apache2/conf.d/20-bz2.ini,
	/etc/php/8.2/apache2/conf.d/20-calendar.ini,
	/etc/php/8.2/apache2/conf.d/20-ctype.ini,
	/etc/php/8.2/apache2/conf.d/20-curl.ini,
	/etc/php/8.2/apache2/conf.d/20-dom.ini,
	/etc/php/8.2/apache2/conf.d/20-exif.ini,
	/etc/php/8.2/apache2/conf.d/20-ffi.ini,
	/etc/php/8.2/apache2/conf.d/20-fileinfo.ini,
	/etc/php/8.2/apache2/conf.d/20-ftp.ini,
	/etc/php/8.2/apache2/conf.d/20-gd.ini,
	/etc/php/8.2/apache2/conf.d/20-gettext.ini,
	/etc/php/8.2/apache2/conf.d/20-gmp.ini,
	/etc/php/8.2/apache2/conf.d/20-iconv.ini,
	/etc/php/8.2/apache2/conf.d/20-igbinary.ini,
	/etc/php/8.2/apache2/conf.d/20-imagick.ini,
	/etc/php/8.2/apache2/conf.d/20-imap.ini,
	/etc/php/8.2/apache2/conf.d/20-intl.ini,
	/etc/php/8.2/apache2/conf.d/20-ldap.ini,
	/etc/php/8.2/apache2/conf.d/20-mbstring.ini,
	/etc/php/8.2/apache2/conf.d/20-msgpack.ini,
	/etc/php/8.2/apache2/conf.d/20-mysqli.ini,
	/etc/php/8.2/apache2/conf.d/20-pdo_mysql.ini,
	/etc/php/8.2/apache2/conf.d/20-phar.ini,
	/etc/php/8.2/apache2/conf.d/20-posix.ini,
	/etc/php/8.2/apache2/conf.d/20-readline.ini,
	/etc/php/8.2/apache2/conf.d/20-redis.ini,
	/etc/php/8.2/apache2/conf.d/20-shmop.ini,
	/etc/php/8.2/apache2/conf.d/20-simplexml.ini,
	/etc/php/8.2/apache2/conf.d/20-sockets.ini,
	/etc/php/8.2/apache2/conf.d/20-sysvmsg.ini,
	/etc/php/8.2/apache2/conf.d/20-sysvsem.ini,
	/etc/php/8.2/apache2/conf.d/20-sysvshm.ini,
	/etc/php/8.2/apache2/conf.d/20-tokenizer.ini,
	/etc/php/8.2/apache2/conf.d/20-xmlreader.ini,
	/etc/php/8.2/apache2/conf.d/20-xmlwriter.ini,
	/etc/php/8.2/apache2/conf.d/20-xsl.ini,
	/etc/php/8.2/apache2/conf.d/20-zip.ini,
	/etc/php/8.2/apache2/conf.d/25-memcached.ini 
```

**Comment by jerrywham** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
librsvg2-bin is already the newest version (2.54.7+dfsg-1~deb12u1).
pdftk is already the newest version (2.02-5+b1).
imagemagick is already the newest version (8:6.9.11.60+dfsg-1.6).
potrace is already the newest version (1.16-2).
ghostscript is already the newest version (10.0.0~dfsg-11+deb12u2).
locales is already the newest version (2.36-9+deb12u3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by jerrywham** [comment]
J'ai également lancé `dpkg-reconfigure locales` et redémarré apache, mais ça n'a rien changé.

**Comment by jerrywham** [comment]
J'ai trouvé. Il a fallu que je redémarre *vraiment* apache pour que ça fonctionne, après la reconfiguration des locales du serveur.
Je ne faisait qu'un reload et non pas un stop/start.

Et il faut également choisir fr-FR et non fr-FR.utf8 dans le "configurateur".

Du coup, le problème venait de chez moi.
Si ça peut servir,..

**Comment by wincelau** [comment]
> Si ça peut servir,..

Oui, merci d'avoir partager le problème que tu as rencontré et sa solution, j'ai rajouté une section "Troubleshootig" dans l'installation : https://github.com/24eme/signaturepdf/blob/master/installation.md#troubleshooting

Par contre j'ai regardé sur ma machine et sur l'instance 24ème et c'est en  "fr_FR.UTF-8", du coup je précise rien la dessus car je ne sais pas trop ce qui est le mieux.
