### ISSUE TITLE
Editer les métadonnées ne fonctionne pas

### ISSUE THREAD

**Issue by L041S** [24eme/signaturepdf#54]
Bonjour,
J'ai installé le service et tout fonctionne parfaitement sauf l'édition de métadonnées. Voici les captures de l'interface : il n'y a pas la possibilité de choisir un PDF ou d'utiliser celui de l'exemple contrairement aux autres onglets. 

(version installée : 1.3.0)

Merci par avance pour votre aide !

![Capture d’écran du 2023-04-20 23-49-30](https://user-images.githubusercontent.com/60223861/233495049-11bf7871-eee0-4d4e-8814-1532c50f2e52.png)
![Capture d’écran du 2023-04-20 23-49-35](https://user-images.githubusercontent.com/60223861/233495051-3791abb9-b1a3-432c-8059-d11ddf142f0b.png)

Edit : en analysant la page avec la console, le problème semble venir du document "metadata", j’ai le message "erreur 500 underfined variable $maxSize" juste après "le document PDF ne doit  pas dépasser"

**Comment by wincelau** [comment]
Merci pour ce retour et l'analyse (ma conf php n'affichait pas ce message) qui m'a permis de corriger le problème : 30e7ffef892be9b7568b4e01d0dc68ec7395bcd0
