### ISSUE TITLE
Utiliser $PDF_DEMO_LINK=True ne fonctionne pas.

### ISSUE THREAD

**Issue by chabotsi** [24eme/signaturepdf#56]
Le README et le Dockerfile indiquent que la valeur par défaut de PDF_DEMO_LINK est True. Or, cela ne fonctionne pas.

En lisant le code, notamment [ce commit](https://github.com/24eme/signaturepdf/commit/68be39ed233fe686935792098f1c6375bc621586#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) on s’aperçoit qu’une URL est attendue.

- PDF_DEMO_LINK pourrait être de type `null` ou `string`, plutôt que “False ou string”, cela serait peut être moins ambiguë ?
- peut être changer les valeurs par défaut, pour mettre l’url de l’ancien pdf ? (https://raw.githubusercontent.com/24eme/signaturepdf/master/tests/files/document.pdf)

**Comment by wincelau** [comment]
J'ai tenté avec null ou string, mais je n'ai pas réussi à faire la différence avec fatfree entre le fait que la variable a volontairement été définit à null et la variable n'a pas du tout était définit lorsque le fichier config.ini n'a pas été créé ou que l'option est commenté.

Et pour l'url par défaut en option, j'y ai pensé aussi mais je ne suis pas trop fan à l'idée de changer le comportement des instances qui sont déjà en place notamment celles qui auraient fait le choix de ne pas avoir de fichier de conf par défaut ou qui ne passe pas par docker.

Par contre j'ai corrigé le bug :) : 7e2aa0fe3122b7390ca7a0313d21f52018ee209d
