### ISSUE TITLE
[Docker] Image cassée depuis la version 1.3.0

### ISSUE THREAD

**Issue by nanawel** [24eme/signaturepdf#57]
Bonjour,

Tout d'abord, merci pour cette app très utile :heart:

Je pense qu'il y a un problème suite à la modification du Dockerfile et de l'ajout de l'instruction `USER www-data` depuis la v1.3.0.
En effet cela rentre en conflit avec l'`entrypoint.sh` qui précise : 

```shell
envsubst < /usr/local/signaturepdf/config/apache.conf > /etc/apache2/sites-available/signaturepdf.conf
envsubst < /usr/local/signaturepdf/config/php.ini > /usr/local/etc/php/conf.d/uploads.ini
envsubst < /usr/local/signaturepdf/config/config.ini.tpl > /usr/local/signaturepdf/config/config.ini
chown -R www-data:www-data /usr/local/signaturepdf && chmod 750 -R /usr/local/signaturepdf
```

Au démarrage on se retrouve donc avec ces erreurs :
```
signaturepdfdocker-app-1  | /usr/local/signaturepdf/entrypoint.sh: line 3: /etc/apache2/sites-available/signaturepdf.conf: Permission denied
signaturepdfdocker-app-1  | /usr/local/signaturepdf/entrypoint.sh: line 5: /usr/local/etc/php/conf.d/uploads.ini: Permission denied
signaturepdfdocker-app-1  | /usr/local/signaturepdf/entrypoint.sh: line 7: /usr/local/signaturepdf/config/config.ini: Permission denied
signaturepdfdocker-app-1  | chown: changing ownership of '/usr/local/signaturepdf/config/config.ini': Operation not permitted
```
car évidemment `www-data` n'a pas les droits pour faire ces modifications sur le filesystem.

L'accès à l'appli par le navigateur retourne ensuite une 403 car c'est le vhost par défaut qui répond.

ping @xgaia qui avait mis en place le build Docker si je ne me trompe pas.

**Comment by xgaia** [comment]
Bonjour @nanawel , j'ai ouvert une PR pour réparé le problème : https://github.com/24eme/signaturepdf/pull/55

**Comment by nanawel** [comment]
Ah super j'avais pas vu, j'ai cherché dans le issues mais pas dans les PR :sweat:
