### ISSUE TITLE
Pouvoir tracer un trait pour rayer une mention

### ISSUE THREAD

**Issue by kmorinCL** [24eme/signaturepdf#62]
Votre outil est cool, il manque juste pour ma part de pouvoir faire un trait pour rayer une mention inutile.

**Comment by jerrywham** [comment]
Tu as deux possibilités au moins pour le faire :
* soit utiliser l'option paraphe et utiliser une succession de tirets ------------- que tu déplaces où tu veux
* soit importer l'image d'un trait que tu déplaces où tu veux

**Comment by wincelau** [comment]
C'est désormais possible :) https://github.com/24eme/signaturepdf/commit/da02c2a37ac351a03af250fa9133c25da9c29612
