### ISSUE TITLE
Erreur d'accès au cache. Cette application ne fonctionne pas en mode de navigation privée

### ISSUE THREAD

**Issue by MedShake** [24eme/signaturepdf#69]
Bonjour,

Merci pour cette excellente app !

Un essai de déploiement sur mon homeserver local via docker me donne le message d'erreur indiqué en titre de ce post, en popup à l'ouverture de l'url.

docker run -d --name=signaturepdf -p 8080:80 -e SERVERNAME=192.168.1.56 signaturepdf

Je précise bien sûr que je ne suis pas en mode navigation privée. 
Test réalisé sous Firefox et Chromium.

B.

**Comment by shad00m** [comment]
Getting the same error in french

**Comment by wincelau** [comment]
Are you using https? Does the cache you're using only work in https or with localhost ?

Could you see if you have an error in the console (F12) ?

**Comment by jerrywham** [comment]
I have the same issue with private navigation. The console error is 
```js
DOMException: The operation is insecure.
    pageUpload https://pdfsign.ecyseo.fr/js/signature.js?03efc49:1042
    <anonymous> https://pdfsign.ecyseo.fr/js/signature.js?03efc49:1159
    <anonymous> https://pdfsign.ecyseo.fr/js/signature.js?03efc49:1164
signature.js:1044:17
```

**Comment by wincelau** [comment]
Ok j'ai testé, c'est parce que l'application utilise le [cache api](https://developer.mozilla.org/en-US/docs/Web/API/Cache) de du navigateur pour stocker le pdf (https://github.com/24eme/signaturepdf/blob/master/public/js/signature.js#L1042).  Et ce module de cache fonctionne seulement avec une connexion sécurisé https et pas en http sauf en localhost.

Il ne fonctionne pas non plus en navigation privé c'est pourquoi c'est le message "Erreur d'accès au cache. Cette application ne fonctionne pas en mode de navigation privée"

Si tu testes avec localhost ça devrait fonctionner.

```docker run -d --name=signaturepdf -p 8080:80 -e SERVERNAME=localhost signaturepdf````

Ce qui serait bien ce serait de faire évoluer le javascript pour rendre l'utilisation du module cache uniquement si c'est possible, quitte à dégrader un peu le fonctionnement et éviter ce genre de problèmes.

**Comment by wincelau** [comment]
Je viens de faire en sorte que l'application fonctionne aussi sans le cache et donc en en navigation 

ac8dba4ba09 55176b91cb765 ed7d2f9acd209299a577d1dc29aabe115c78693f
