### ISSUE TITLE
Sequanux instance

### ISSUE THREAD

**Issue by lolivz** [24eme/signaturepdf#91]
Super outil, nous l'avons rajouté à la liste des services de notre 'chaton' https://chaton.sequanux.org/fr
Accès public via https://pdf.sequanux.org/

**Comment by wincelau** [comment]
Trop bien :), je l'ai rajouté dans le readme: https://github.com/24eme/signaturepdf/commit/edac0be8af47750fd4e640310ea60a817b4a8dd9
